FROM python:2.7-alpine3.6

RUN apk add --no-cache --virtual .build-deps \
        g++ \
        git \
        python2-dev \
    && apk add --no-cache \
        bash \
    && pip install --no-cache-dir --upgrade \
        pip \
        'Markdown>=2.6.9' \
        'mkdocs>=0.16.3' \
        'mkdocs-material>=1.10.1' \
        'markdown-include>=0.5.1' \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/*
